version: '3.7'

services:
  ### Apache ##############################################
  httpd:
    build: ./httpd
    container_name: httpd
    ports:
      - 80:80
    privileged: true
    volumes:
      - ./workspace:/var/www/html
      - ./httpd/vhost.conf:/etc/httpd/conf.d/vhost.conf
      - ./httpd/httpd.conf:/etc/httpd/conf/httpd.conf
  ### MySQL ##############################################
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --server-id=1
    ports:
      - 3306:3306
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql

