version: "3.7"

services:
  ### PHP & Apache ##############################################
  php-apache:
    build: ./php-apache
    container_name: php-apache
    ports:
      - 80:80
      - 50030:50030
    privileged: true
    volumes:
      - ./workspace:/var/www/html
      - ./php-apache/php.ini:/usr/local/etc/php/php.ini
      - ./php-apache/msmtprc:/etc/msmtprc
  ### MySQL ##############################################
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - 3306:3306
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
  ### Redis ##############################################
  redis:
    image: "redis:5.0.5"
    container_name: "redis"
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
  ### Mailcatcher ##############################################
  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
